      SUBROUTINE DIRICHLETSECONDMEMBRE(N,M,VECTEUR_TRIANGLE,
     G VECTEUR_BOUND,CONDDIRIC,VECTEURX,VECTEURY,
     L VECTEUR_SECONDMEMBRE)
      IMPLICIT NONE
      INTEGER  I,N,M,POS,ITERATOR,VECTEUR_TRIANGLE((N+1)*(M+1)),
     A VECTEUR_BOUND(2*(M+N+1)),CONDDIRIC
      REAL  VECTEUR_SECONDMEMBRE((N+1)*(M+1)),FJ(3),CONDNE(4)
     F ,VECTEURX(N+1),VECTEURY(M+1),BOUNDX,BOUNDY

      DO 1 I=1,N+1
      IF(CONDDIRIC.EQ.1) THEN
      BOUNDX = VECTEURX(VECTEUR_BOUND(I))
      BOUNDY = VECTEURY(VECTEUR_BOUND(I))
      ELSE IF(CONDDIRIC.EQ.2) THEN
      BOUNDX = VECTEURX(VECTEUR_BOUND(I))*VECTEURX(VECTEUR_BOUND(I))
      BOUNDY = VECTEURY(VECTEUR_BOUND(I))*VECTEURY(VECTEUR_BOUND(I))
      ENDIF
    
      POS = VECTEUR_BOUND(I)
      VECTEUR_SECONDMEMBRE(POS) = BOUNDX
      WRITE(*,*) 'GAMA1: ',POS,'BOUNDX',BOUNDX
1     CONTINUE


      DO 4 I=2*(N+1)+M+2,2*(N+M+2)
      IF(CONDDIRIC.EQ.1) THEN
      BOUNDX = VECTEURX(VECTEUR_BOUND(I))
      BOUNDY = VECTEURY(VECTEUR_BOUND(I))
      ELSE IF(CONDDIRIC.EQ.2) THEN
      BOUNDX = VECTEURX(VECTEUR_BOUND(I))*VECTEURX(VECTEUR_BOUND(I))
      BOUNDY = VECTEURY(VECTEUR_BOUND(I))*VECTEURY(VECTEUR_BOUND(I))
      ENDIF
      POS = VECTEUR_BOUND(I)
      VECTEUR_SECONDMEMBRE(POS) = BOUNDY
      WRITE(*,*) 'GAMA4: ',POS,'BOUNDX',BOUNDY
4     CONTINUE


      END
